site_name: SpagoBI 
site_url: https://spagobi.readthedocs.org
repo_url: https://github.com/EngineeringSPA/SpagoBI.git
site_description: SpagoBI Documentation
docs_dir: doc
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["http://fiware.org/style/monokai_sublime.css"]
pages:
- 'Home': 'index.md'
- 'User & Programmers Manuals':
    - 'CKAN': 'user/CKAN/README.md'
    - 'Javascript SDK': 'user/JS/README.md'
    - 'NGSI': 'user/NGSI/README.md'
- 'Admin Manuals':
    - 'Admin Guide': 'admin/README.md'
    - 'Sanity check procedures': 'admin/sanity.md'
- 'Docker' : 'docker/README.md'
